### ISSUE TITLE
Constructing OData endpoints

### ISSUE THREAD

**Issue by jamesholcomb** [dkackman/DynamicRestProxy#4]
`http://localhost/api/customers?$top=3`

how do you compose this as `$top` is not a valid function argument?

**Comment by dkackman** [comment]
There are a few escape mechanisms built in. For names that are c# keywords you can escape them inline with @. like @long. For your case you can pass a Dictionary<string,object> as an unnamed parameter if you have parameter names that are not valid C# names. I'm considering using Tuple<string, object> to do the same thing as it may be a little less cumbersome but this should work for you

    using (dynamic client = new DynamicRestClient("http://localhost/"))
    {
        var args = new Dictionary<string, object>
        {
            { "$top", 3 }
        };
        var result = await client.api.customers.get(args);
        Assert.IsNotNull(result);
    }

**Comment by jamesholcomb** [comment]
Thanks that worked.
