### ISSUE TITLE
Setting DefaultRequestHeader.Authorization

### ISSUE THREAD

**Issue by jamesholcomb** [dkackman/DynamicRestProxy#5]
What is the recommended way to set the internal

`HttpClient.DefaultRequestHeader.Authorization = new AuthenticationHeaderValue("Bearer", token);` 

_after_ construction of a `DynamicRestClient`?

For instance, I would like to create an API specific wrapper which exposes a `DynamicRestClient`.  The wrapper would implement an `Authenticate(user, password)` method to request an OAuth bearer token for subsequent REST calls.  The wrapper exposes a constructor which takes an `HttpClient` to create the `DynamicRestClient`.

**Comment by dkackman** [comment]
Use the constructor of DynamicRestClient that takes a DynamicRestClientDefaults object. You can set the scheme and token there and it will be used set on the default request header as you have about.

This is from the [google cloud storage unit tests](https://github.com/dkackman/DynamicRestProxy/blob/master/Client.Google.UnitTests/CloudStorageTests.cs) (the auth objects are unit test helpers and not part of the client assembly but however you get the bearer token you would set it like below)

    var auth = MockInitialization.GetAuthClient("email profile https://www.googleapis.com/auth/devstorage.read_write");
    var token = await auth.Authenticate(token);
    Assert.IsNotNull(token, "auth failed");

    var defaults = new DynamicRestClientDefaults()
    {
        AuthScheme = "OAuth",
        AuthToken = token
    };
    using (dynamic google = new DynamicRestClient("https://www.googleapis.com/", MockInitialization.Handler, false, defaults))
    using (var stream = new StreamInfo(File.OpenRead(@"D:\temp\test.png"), "image/png"))
    {
        dynamic result = await google.upload.storage.v1.b.unit_tests.o.post(stream, name: new PostUrlParam("test_object"), uploadType: new PostUrlParam("media"));
        Assert.IsNotNull(result);
    }
