### ISSUE TITLE
Response properties

### ISSUE THREAD

**Issue by jamesholcomb** [dkackman/DynamicRestProxy#6]
Is there a way to obtain properties of the response (http status code, headers) from the previous operation?

**Comment by dkackman** [comment]
Yes. You can get the full HttpResponseMessage back from any verb by passing typeof(HttpResponseMessage) as an unnamed argument.  It is up to you to deserialize the content and dispose the response object.

Take a look at the [ReturnHttpResponseMessage unit test](https://github.com/dkackman/DynamicRestProxy/blob/master/DynamicRestPRoxy.Portable.UnitTests/TypedDeserializationTests.cs).

You can use this same mechanism to get the content as a stream, byte[], string or a static type of your choosing.

**Comment by jamesholcomb** [comment]
What are you thoughts on throwing a specific exception (e.g. DynamicRestClientException) that contains details of the http response?  Typically I only care about it on non-success in order to get the server error from the response content.

**Comment by dkackman** [comment]
Sounds like a reasonable idea. I'll take a look at it next week.
